import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import { NetworkProvider } from "@/contexts/NetworkContext";
import "./globals.css";

// Body/heading font is Switzer, loaded via the @import in globals.css (see
// the comment there for why: Switzer isn't on Google Fonts, so next/font
// can't load it). Geist Mono stays on next/font and stays the mono
// typeface -- wallet addresses, tx hashes and base-unit numbers need a
// real monospace face to stay aligned/legible, so that one usage was kept
// instead of switching everything to Switzer.
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <NetworkProvider>{children}</NetworkProvider>
      </body>
    </html>
  );
}
